name: Build

on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build -c Release --no-restore
            - name: Test Debug
              run: dotnet test -c Debug --no-restore --verbosity normal --collect:"XPlat Code Coverage"
            - name: Test Release
              run: dotnet test -c Release --no-restore --verbosity normal --collect:"XPlat Code Coverage"